# Generated by Django 6.0.4 on 2026-04-07 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_book_language_book_vendor_bookreview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="books/covers/"),
        ),
    ]
