# Generated by Django 6.0.4 on 2026-04-19 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_alter_book_cover_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="is_bestseller",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="book",
            name="is_popular",
            field=models.BooleanField(default=False),
        ),
    ]
