# Generated by Django 6.0.4 on 2026-04-19 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_bestseller_popular_flags"),
    ]

    operations = [
        migrations.AddField(
            model_name="mood",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="moods/"),
        ),
    ]
