# Generated by Django 6.0.4 on 2026-06-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_mood_images"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="cover_image",
        ),
        migrations.RemoveField(
            model_name="mood",
            name="image",
        ),
        migrations.AddField(
            model_name="book",
            name="cover_image_url",
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="mood",
            name="image_url",
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
