# Generated by Django 6.0.4 on 2026-09-20 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_remove_book_cover_image_remove_mood_image_and_more"),
        ("vendors", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="book",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="books",
                to="vendors.vendor",
            ),
        ),
        migrations.CreateModel(
            name="BookCombo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "combo_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Final price for the entire combo bundle",
                        max_digits=10,
                    ),
                ),
                (
                    "cover_image_url",
                    models.URLField(
                        blank=True,
                        help_text="Optional banner/cover image for the combo",
                        max_length=1024,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "books",
                    models.ManyToManyField(related_name="combos", to="store.book"),
                ),
            ],
            options={
                "verbose_name": "Book Combo",
                "verbose_name_plural": "Book Combos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Internal label e.g. 'Odia Month Sale'",
                        max_length=255,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="Coupon code customers enter. Leave blank to auto-generate.",
                        max_length=30,
                        unique=True,
                    ),
                ),
                (
                    "offer_type",
                    models.CharField(
                        choices=[
                            ("PERCENTAGE", "Percentage Discount (%)"),
                            ("FLAT", "Flat Amount Off (₹)"),
                            ("COMBO_EXTRA", "Extra % Off on Combos"),
                        ],
                        default="PERCENTAGE",
                        max_length=20,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percentage (%) or flat ₹ amount depending on type",
                        max_digits=6,
                    ),
                ),
                (
                    "minimum_order_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Minimum cart value required to apply this offer (0 = no minimum)",
                        max_digits=10,
                    ),
                ),
                (
                    "max_discount_cap",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Max ₹ discount for percentage types. Leave blank = unlimited",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("valid_from", models.DateTimeField()),
                ("valid_until", models.DateTimeField()),
                (
                    "usage_limit",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Total redemptions allowed. Leave blank = unlimited",
                        null=True,
                    ),
                ),
                (
                    "per_user_limit",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Max times a single user can redeem this code",
                    ),
                ),
                ("times_used", models.PositiveIntegerField(default=0, editable=False)),
                (
                    "applies_to_combos_only",
                    models.BooleanField(
                        default=False,
                        help_text="Discount applies only to combo items in cart",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "applies_to_category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Restrict discount to a category. Leave blank = store-wide",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="store.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Offer / Coupon",
                "verbose_name_plural": "Offers & Coupons",
                "ordering": ["-created_at"],
            },
        ),
    ]
