# Generated by Django 6.0.4 on 2026-09-20 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_alter_book_options_alter_book_vendor_bookcombo_offer"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="image_2_url",
            field=models.URLField(
                blank=True,
                help_text="Product Image 2 (500x500)",
                max_length=1024,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="image_3_url",
            field=models.URLField(
                blank=True,
                help_text="Product Image 3 (500x500)",
                max_length=1024,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="cover_image_url",
            field=models.URLField(
                blank=True,
                help_text="Primary Cover Image (500x500)",
                max_length=1024,
                null=True,
            ),
        ),
    ]
