# Generated by Django 6.0.4 on 2026-09-21 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_book_image_2_url_book_image_3_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MagazineEdition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="e.g. Abhilasha Annual Literary Edition 2026",
                        max_length=255,
                    ),
                ),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "edition_year",
                    models.CharField(
                        default="2026", help_text="e.g. 2026, 2025-26", max_length=20
                    ),
                ),
                (
                    "issue_number",
                    models.CharField(
                        default="Annual Edition",
                        help_text="e.g. Annual Edition, Vol. 14",
                        max_length=50,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("BI", "Bilingual (Odia & Hindi)"),
                            ("OD", "Odia (ଓଡ଼ିଆ)"),
                            ("HI", "Hindi (हिन्दी)"),
                            ("EN", "English"),
                        ],
                        default="BI",
                        max_length=2,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Editorial theme, contents, highlights, and featured authors"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=199.0, max_digits=10),
                ),
                (
                    "discount_percentage",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "stock",
                    models.PositiveIntegerField(
                        default=50, help_text="Available print copies"
                    ),
                ),
                (
                    "cover_image_url",
                    models.URLField(
                        blank=True,
                        help_text="Primary Cover (500x500)",
                        max_length=1024,
                        null=True,
                    ),
                ),
                (
                    "image_2_url",
                    models.URLField(
                        blank=True,
                        help_text="Inner Page / TOC Preview (500x500)",
                        max_length=1024,
                        null=True,
                    ),
                ),
                (
                    "image_3_url",
                    models.URLField(
                        blank=True,
                        help_text="Back Cover / Editorial Preview (500x500)",
                        max_length=1024,
                        null=True,
                    ),
                ),
                (
                    "is_current_edition",
                    models.BooleanField(
                        default=False,
                        help_text="Highlight as the current flagship annual edition",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "total_pages",
                    models.PositiveIntegerField(blank=True, default=128, null=True),
                ),
                (
                    "chief_editor",
                    models.CharField(
                        blank=True, default="Abhilasha Editorial Board", max_length=255
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Magazine Edition",
                "verbose_name_plural": "Magazine Editions",
                "ordering": ["-edition_year", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MagazineSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=20)),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("OD", "Odia (ଓଡ଼ିଆ)"),
                            ("HI", "Hindi (हिन्दी)"),
                            ("EN", "English"),
                        ],
                        default="OD",
                        max_length=2,
                    ),
                ),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("POETRY", "Poetry / କବିତା / कविता"),
                            ("STORY", "Short Story / ଗଳ୍ପ / लघु कथा"),
                            ("ESSAY", "Essay / ପ୍ରବନ୍ଧ / निबंध"),
                            ("ARTICLE", "Literary & Cultural Article / ସାହିତ୍ୟିକ ଆଲେଖ୍ୟ"),
                        ],
                        default="POETRY",
                        max_length=20,
                    ),
                ),
                ("title_of_work", models.CharField(max_length=255)),
                (
                    "content_text",
                    models.TextField(
                        help_text="The submitted writing text or synopsis"
                    ),
                ),
                (
                    "author_bio",
                    models.TextField(
                        blank=True, help_text="Short bio and address/district"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "Received / ପ୍ରାପ୍ତ"),
                            ("UNDER_REVIEW", "Under Review / ବିଚାରାଧୀନ"),
                            ("SELECTED", "Selected for Publication / ମନୋନୀତ"),
                            ("PUBLISHED", "Published / ପ୍ରକାଶିତ"),
                            ("REJECTED", "Not Selected"),
                        ],
                        default="RECEIVED",
                        max_length=20,
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True, help_text="Internal notes by editorial board"
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Magazine Submission",
                "verbose_name_plural": "Magazine Submissions",
                "ordering": ["-submitted_at"],
            },
        ),
    ]
