# Generated by Django 6.0.4 on 2026-09-26 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_magazineedition_magazinesubmission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="is_bestseller",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="book",
            name="is_odisha_heritage",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="book",
            name="is_popular",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="book",
            name="is_trending_in_odisha",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="book",
            name="language",
            field=models.CharField(
                choices=[("OD", "Odia"), ("EN", "English"), ("HI", "Hindi")],
                db_index=True,
                default="EN",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="stock",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
