# Generated by Django 6.0.4 on 2026-09-27 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0010_alter_book_created_at_alter_book_is_bestseller_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="e.g. Odia Heritage Wooden Bookmark, Golden Nib Bookmark",
                        max_length=255,
                    ),
                ),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Material, dimensions, theme, and craftsmanship details",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=49.0,
                        help_text="Original Price (e.g. ₹35 - ₹99)",
                        max_digits=10,
                    ),
                ),
                (
                    "discount_percentage",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "stock",
                    models.PositiveIntegerField(
                        default=50, help_text="Available inventory units"
                    ),
                ),
                (
                    "cover_image_url",
                    models.URLField(
                        blank=True,
                        help_text="Primary Image (500x500)",
                        max_length=1024,
                        null=True,
                    ),
                ),
                (
                    "image_2_url",
                    models.URLField(
                        blank=True,
                        help_text="Secondary Image (500x500)",
                        max_length=1024,
                        null=True,
                    ),
                ),
                (
                    "image_3_url",
                    models.URLField(
                        blank=True,
                        help_text="Tertiary Image (500x500)",
                        max_length=1024,
                        null=True,
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Highlight on store homepage / showcase",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Bookmark",
                "verbose_name_plural": "Bookmarks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="magazinesubmission",
            options={},
        ),
    ]
