# Generated by Django 6.0.4 on 2026-04-20 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                ("value", models.CharField(max_length=50)),
                (
                    "numeric_value",
                    models.FloatField(
                        default=0,
                        help_text="Numeric part for 'start from zero' animation",
                    ),
                ),
                (
                    "suffix",
                    models.CharField(
                        blank=True, help_text="e.g. '+', '★', ' hrs'", max_length=20
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
