# Generated by Django 6.0.4 on 2026-09-21 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReaderStory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "location",
                    models.CharField(default="Bhubaneswar, Odisha", max_length=150),
                ),
                ("rating", models.PositiveIntegerField(default=5)),
                ("review_text", models.TextField()),
                ("is_approved", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Reader Story",
                "verbose_name_plural": "Reader Stories",
                "ordering": ["-created_at"],
            },
        ),
    ]
