# Generated by Django 6.0.4 on 2026-06-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_payment_method_order_payment_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("WHATSAPP", "WhatsApp Order")],
                default="WHATSAPP",
                max_length=20,
            ),
        ),
    ]
