# Generated by Django 6.0.4 on 2026-09-20 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_combocartitem_comboorderitem_alter_order_options_and_more"),
        ("store", "0007_alter_book_options_alter_book_vendor_bookcombo_offer"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="coupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="store.offer",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="coupon_code_used",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="order",
            name="discount_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="order",
            name="final_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(default="WHATSAPP", max_length=20),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Confirmed", "Confirmed"),
                    ("Processing", "Processing"),
                    ("Shipped", "Shipped"),
                    ("Delivered", "Delivered"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together={("cart", "book")},
        ),
        migrations.AddField(
            model_name="combocartitem",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="combo_items",
                to="orders.cart",
            ),
        ),
        migrations.AddField(
            model_name="combocartitem",
            name="combo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="store.bookcombo"
            ),
        ),
        migrations.AddField(
            model_name="comboorderitem",
            name="combo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="store.bookcombo"
            ),
        ),
        migrations.AddField(
            model_name="comboorderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="combo_items",
                to="orders.order",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="combocartitem",
            unique_together={("cart", "combo")},
        ),
    ]
